######### Cadastro Informaçao
POST http://127.0.0.1:3333/informacoes HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.dFpagNMIoTlmfyi5-m4tjHLPQuTv1aEpep89KVkUq_APq5sUc2biTHO0hWaW
{
    "time": "Brooklyn Nets",
    "temporada": "2021",
    "vitorias" : "100"
}

######### Listar todos as Informaçoes
GET http://127.0.0.1:3333/informacoes HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.dFpagNMIoTlmfyi5-m4tjHLPQuTv1aEpep89KVkUq_APq5sUc2biTHO0hWaW


######### Listar Informaçao específica
GET http://127.0.0.1:3333/informacoes/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.dFpagNMIoTlmfyi5-m4tjHLPQuTv1aEpep89KVkUq_APq5sUc2biTHO0hWaW

######### Alterar Informaçao
PUT http://127.0.0.1:3333/informacoes/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.dFpagNMIoTlmfyi5-m4tjHLPQuTv1aEpep89KVkUq_APq5sUc2biTHO0hWaW

{
    "time": "Brooklyn Nets",
    "temporada": "2022",
    "vitorias" : "80"
}

######### Apagar Informaçao
DELETE http://127.0.0.1:3333/informacoes/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.dFpagNMIoTlmfyi5-m4tjHLPQuTv1aEpep89KVkUq_APq5sUc2biTHO0hWaW